export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'



export const COURSE_REGISTERED_REQUEST = 'COURSE_REGISTERED_REQUEST'
export const COURSE_REGISTERED_SUCCESS = 'COURSE_REGISTERED_SUCCESS'
export const COURSE_REGISTERED_FAIL = 'COURSE_REGISTERED_FAIL'


